### ISSUE TITLE
question: surprising performance

### ISSUE THREAD

**Issue by spock** [Kwarf/rotsniff#1]
Hi,

I'm looking for a hash verification tool for my photos/videos collection, and came across `rotsniff`.

I've already had a look at some other projects, including https://github.com/laktak/chkbit-py - which is written in Python and uses md5. On my folder (400+ gbytes, 50k+ files) it finished building a database in 7 minutes (using 6 workers = num of my physical cores; with a single worker, it needed 30 minutes).

As far as I understand, `blake2` is faster than `md5`, and Rust is faster than Python.
However, `rotsniff` actually took much, much longer on my data: **52 minutes**
The command I'm running is just `rotsniff append .`

And that is the question: is it supposed to take that much longer?
My uninformed gut feeling is that something is wrong :)

My observations:

- `rotsniff` starts with a rather high CPU usage, so I assume it is multi-threaded by default; looks like 12 threads (= number of virtual cores) are created
- SSD **read speeds are much lower** than for the python tool; speed seems to be capped at around 150-160 mbytes/sec (while python tool definitely had 500+ mbytes/sec peaks). While read speed is low, SSD activity (number of requests) is very high. I wonder if there is a too small reading buffer somewhere? (This is further suggested by threads spending lots of time in a waiting state...)
- **very high RAM usage**: up to 30GB VIRT and 15 GB RES (based on a random `htop` observation for a minute or so); it does decrease at times, but seems to be in multi-gigabyte (4-6+ or so?) RES range at all times.

**Comment by spock** [comment]
There is definitely something wrong, the question now is where exactly to look for a problem: my setup, my build, or the source code.

`rotsniff verify` appears to behave the same (slow reading); I did not wait for a full run.

**Comment by Kwarf** [comment]
Hi,

First of all I'd like to thank you for a very well-written issue. 🤩

I have not been using this tool myself for quite a while, since I've since switched to running [btrfs](https://en.wikipedia.org/wiki/Btrfs) on my NAS, relying on that for snapshots and checksumming instead. But I still got curious from all your testing and decided to take a look at it.

When initially choosing how to read the data I decided to use `mmap`, thinking that it would be fastest letting the kernel handle all the reads and the buffering. It also simplified my use of the [blake2](https://crates.io/crates/blake2) crate. This explains the high _virtual_ memory use, since the entire file would be counted there without _actually_ using that much RAM.

However as often is the case, guessing without measuring can often result in incorrect assumptions. 😅

I decided to test rewriting it to use a `BufReader` instead, which by default creates an 8kB read buffer over the file, and then I call the hash library with blocks matching what it works over (128B). This made a huge difference in speed.

### Benchmarks

I created 12 separate 10GB files from `/dev/urandom` data on my MacBook Pro, and when running the **previous** version ended up with around 1,7 - 2 GB/s reads, and a bit over a minute to finish.

```
rotsniff append .  123.92s user 69.61s system 272% cpu 1:11.13 total
```

Doing the same test using the new buffered version I got sustained 6,7 GB/s reads, which is probably the cap of what the SSD is capable of, and it finished in just over 20 seconds instead.

```
rotsniff append .  155.64s user 39.84s system 949% cpu 20.597 total
```

So if you'd like you can get the new `v0.2.0` from crates.io with `cargo install rotsniff` and let me know if you see any improvements in speed. But I do want to make a disclaimer that this project is not very tested or maintained, so if you find another more popular project that meets your demands I would probably recommend you use that instead. 😅

**Comment by spock** [comment]
Thanks for the quick fix! 😊

It does indeed increase speed also for me, although only about 2x. Maybe increasing the buffer will further increase speed, but at some point there will be a trade-off with big/small files.
It is also quite possible that the way I currently run it (WSL2) is somehow more affected than the python version.
In any case, I think this isn't worth further effort.

Memory usage is now down to 8 KB RES... Would be difficult to beat 😄 

For now that python tool matches my other requirements better, I was just very surprised with counter-intuitive results.

Thanks!

P.S. / Motivation
I'm using ZFS on my ECC RAM-equipped TrueNAS + file-level encryption on top of it.
This works wonderfully for automatic off-site backups - they don't need any passwords and can simply use `rsync`.
This setup is very good for storage/archival, but for some reason it is way too slow for any kind of editing - and I'm "actively maintaining" the archive, it is live and not static.

So my current idea is to use windows-local encrypted SSD storage, where I do "data maintenance", and then regularly sync to the (encrypted) NAS mount.
Which is why I now need at least some way to monitor for undesired data changes; sync to NAS will only proceed if hash check returns zero.

It's a bit complicated 😄
